// packages/vue-ruler/src/components/Ruler.vue
<template>
  <div ref="rulerElement"></div>
</template>
<script lang="ts">
import VanillaRuler, { RulerProps, PROPERTIES, METHODS } from "@scena/ruler";
import { isUndefined, IObject } from "@daybrush/utils";

const methods: Record<string, any> = {
    setStyle() {
        const el = this.$refs.rulerElement as HTMLElement;
        const elStyle = el.style as any;
        const style = this.$props.style || { width: "100%", height: "100%" };

        for (const name in style) {
            if (elStyle[name] === style[name]) {
                continue;
            }
            elStyle[name] = style[name];
        }
    },
};

METHODS.forEach((name) => {
  methods[name] = function (this: any, ...args: any[]) {
    return this.$_ruler[name](...args);
  };
});
const watch: Record<string, any> = {};

PROPERTIES.forEach((name) => {
  watch[name] = function (this: any, value: any) {
      if (name === "style") {
          this.setStyle();
      } else {
        this.$_ruler[name] = value;
      }
  };
});
export default {
  name: "ruler",
  methods,
  props: PROPERTIES,
  watch,
  mounted(this: any) {
    const options: Partial<RulerProps> = {};
    const props = this.$props;
    PROPERTIES.forEach((name) => {
      const value = props[name];

      if (!isUndefined(value)) {
        (options as any)[name] = props[name];
      }
    });
    const ruler = new VanillaRuler(this.$refs.rulerElement as HTMLElement, options);
    this.setStyle();

    this.$_ruler = ruler;
  },
  beforeDestroy(this: any) {
    this.$_ruler.destroy();
  },
};

</script>

// packages/svelte-ruler/src/Ruler.svelte
<script lang="ts">
  import VanillaRuler, {
    RulerProps,
    PROPERTIES
  } from "@scena/ruler";

  import {
    onMount,
    onDestroy,
    beforeUpdate,
    afterUpdate,
    tick
  } from "svelte";

  export let style = { width: "100%", height: "100%"};

  declare var $$props: any;
  let options: Partial<RulerProps> = {};
  let ruler: VanillaRuler;
  let rulerElement: HTMLElement;

  function setStyle() {
    const elStyle = rulerElement.style;

    for (const name in style) {
      if (elStyle[name] === style[name]) {
        continue;
      }
      elStyle[name] = style[name];
    }
  }
  beforeUpdate(() => {
    const props = $$props;

    options = {};
    PROPERTIES.forEach(name => {
      if (name === "style") {
        return;
      }
      if (name in props) {
        (options as any)[name] = props[name];
      }
    });
    if (ruler) {
      for (const name in options) {
        ruler[name] = options[name];
      }
      setStyle();
    }
  });
  onMount(() => {
    setStyle();
    ruler = new VanillaRuler(rulerElement, options);
  });
  onDestroy(() => {
    ruler.destroy();
  });

  export function getInstance() {
    return ruler;
  }
</script>

<div class="ruler" bind:this={rulerElement} />
